### ISSUE TITLE
--config flag doesn't work

### ISSUE THREAD

**Issue by samdidos** [ttauveron/git-follow-up#2]
# Actual behavior
Running from the Amd64 binary on Ubuntu 18.04, the --config flag option won't take in consideration the new path of my config, it take the config at the `.git-follow-up/git` path.
```bash
./git-follow-up-linux-amd64 --config /home/samdidos/workspace/perso/config.yml
```
# Expected behavior
Should change config path

**Comment by ttauveron** [comment]
Thanks so much @samdidos for reporting this bug! 
Will be fixing that soon :)
